[package]
name = "anup"
version = "0.1.0"
edition = "2024"

[dependencies]
anime = { version = "0.1.0", path = "../anime", features = ["rate_limit"] }
ansi-to-tui = { version = "8.0.1", features = ["zero-copy"] }
anyhow = "1.0.103"
crossterm = { version = "0.29.0", features = ["event-stream"] }
derive_more = { version = "2.1.1", features = ["deref", "deref_mut", "from"] }
futures = "0.3.32"
indexmap = "2.14.0"
medinpar = { git = "https://github.com/jonathanlmc/medinpar.git", rev = "cfd4fc97cc4ef54f4d1aa44c9e304fdc394dbd36" }
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm", "std", "layout-cache", "macros"] }
ratatui-widgets = { version = "0.3.2", features = ["unstable-rendered-line-info"] }
reqwest = { version = "0.13.4", default-features = false, features = ["native-tls", "charset", "http2", "system-proxy"] }
strsim = "0.11.1"
tap = "1.0.1"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["rt", "macros", "fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23" }
walkdir = "2.5.0"
