query ($id: Int) {
    Media(id: $id, type: ANIME) {
        coverImage {
            extraLarge
        }
        episodes
        format
        id
        mediaListEntry {
            completedAt {
                day
                month
                year
            }
            createdAt
            progress
            repeat
            score
            startedAt {
                day
                month
                year
            }
            status
            updatedAt
        }
        nextAiringEpisode {
            episode
        }
        title {
            english
            native
            romaji
        }
    }
}
