query ($id: Int) {
    Media(id: $id) {
        relations {
            edges {
                relationType
                node {
                    id
                }
            }
        }
    }
}
