query ($search: String) {
    Page(perPage: 100) {
        media(search: $search, type: ANIME) {
            coverImage {
                extraLarge
            }
            episodes
            format
            id
            mediaListEntry {
                completedAt {
                    day
                    month
                    year
                }
                createdAt
                progress
                repeat
                score
                startedAt {
                    day
                    month
                    year
                }
                status
                updatedAt
            }
            nextAiringEpisode {
                episode
            }
            title {
                english
                native
                romaji
            }
        }
    }
}
