[package]
name = "anime_detect"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anime = { version = "0.1.0", path = "../anime", optional = true }
tap = "1.0.1"
thiserror = "2.0.18"
tracing = "0.1.44"
winnow = { version = "1.0.2", default-features = false, features = ["std", "ascii", "simd"] }

[features]
anime_integration = ["dep:anime"]
