[package]
name = "anime"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot = { version = "0.12.5", optional = true }
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.149"
serde_with = "3.16.1"
tap = "1.0.1"
thiserror = "2.0.18"
tokio = { version = "1.49.0", optional = true, features = ["sync"] }
tracing = "0.1.44"

[features]
rate_limit = ["dep:tokio", "dep:parking_lot"]
