name: Test and Upload Release Artifact

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-and-fmt:
    name: Formatting and Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install -y \
            `# for reqwest` \
            libssl-dev \
            `# for ratatui-image` \
            libchafa-dev \
            libglib2.0-dev

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt

      - name: Formatting
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

  test-matrix:
    name: ${{ matrix.platform.os-name }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os-name: Linux, x86_64
            runs-on: ubuntu-latest

          - os-name: Linux, ARM64
            runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev libchafa-dev libglib2.0-dev

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Check
        run: cargo check

      - name: Run tests
        run: cargo test --verbose

      - name: Build (release)
        run: cargo build --release

      - name: Upload release artifact
        uses: actions/upload-artifact@v6
        with:
          name: Release binary (${{ matrix.platform.os-name }})
          path: target/release/anup
          retention-days: 90
